build:
  cuda_version: "12.1.1"
  python_packages:
    - torch==2.7.1
    - inferless==0.2.15
    - pydantic==2.11.7
    - accelerate==1.9.0
    - transformers==4.54.1
    - huggingface-hub==0.34.3
    - hf-transfer==0.1.9
